### ISSUE TITLE
gcite crashes on years with zero counts... fix available...

### ISSUE THREAD

**Issue by JeffreyRacine** [muschellij2/gcite#2]
Greetings,

Minor glitch in gcite but a fix is available… running scripts if there exists a year with a zero count crashes… see https://github.com/jkeirstead/scholar/issues/29… the scholar package had the same issue but that has been patched in devtools::install_github("jefferis/scholar@develop")

Thanks!

**Comment by muschellij2** [comment]
Please send a Pull Request (https://yangsu.github.io/pull-request-tutorial/) - I don't have time at the moment to get to this
