### ISSUE TITLE
rate too quick, generates 503 errors

### ISSUE THREAD

**Issue by matthewberryman** [muschellij2/gcite#4]
Running:
```S
> f = gcite("Derek Abbott", "vqD_0uQAAAAJ")
```
generates:
```
Getting Citation Index table
Getting Overall citations over time
Getting first set of papers
Getting rest of papers
Reading citation pages
   |+++++++++++                                       | 22% ~03m 57s      Error in gcite_citation_page.character(X[[i]], ...) : 
  Service Unavailable (HTTP 503).
In addition: Warning messages:
1: In df$value[df$field %in% "total citations"] <- cites :
  number of items to replace is not a multiple of replacement length
2: In df$value[df$field %in% "total citations"] <- cites :
  number of items to replace is not a multiple of replacement length
3: In df$value[df$field %in% "total citations"] <- cites :
  number of items to replace is not a multiple of replacement length
4: In df$value[df$field %in% "total citations"] <- cites :
  number of items to replace is not a multiple of replacement length
5: In df$value[df$field %in% "total citations"] <- cites :
  number of items to replace is not a multiple of replacement length
6: In df$value[df$field %in% "total citations"] <- cites :
  number of items to replace is not a multiple of replacement length
7: In df$value[df$field %in% "total citations"] <- cites :
  number of items to replace is not a multiple of replacement length
8: In df$value[df$field %in% "total citations"] <- cites :
  number of items to replace is not a multiple of replacement length
```

Too many requests have been made and it's tripped a rate limit in Google, which then returns 503 (forbidden) HTTP errors. I suggest adding in some sort of rate limit between page requests. If there were some hooks in the code to set User-Agent string and cookies (exported from browser) then it's possible to bypass the limit per discussion at https://github.com/ckreibich/scholar.py/issues/52

**Comment by muschellij2** [comment]
Please send a pull request.



John

**Comment by matthewberryman** [comment]
I'm very rusty on R and have limited time (busy on other projects) but I'll give it a quick go...

**Comment by muschellij2** [comment]
I have made some additions, but still do not believe that the cookies will remedy this problem.  

There are additional arguments you can now set to at least get out most of the output you'd like:
```r
f = gcite(user= "vqD_0uQAAAAJ", force = TRUE, read_citations = FALSE)
```

**Comment by matthewberryman** [comment]
(pro tip if you put `#4` in the commit messages then github links them automatically in this issue thread for easier review)

Forcing things in the pblapply   https://github.com/muschellij2/gcite/commit/363835c6eb320be83022e81d4e026917c9555752#diff-3fce1501a142dd1667dd555d7116d278R74
seems really inelegant:
1. You've hit the rate limit so should be mindful of not making more requests, rather than iterating through the rest and ignoring the 503s (as I understand that line does, correct me if I'm wrong).
2. It drops part of the data.

In https://github.com/AcrossTheCloud/gcite I had a go at rate limiting requests by spacing them out using `Sys.sleep(time)`, which then means you can get all the data. However I hit a bug in trying to parameterise with a `sleeptime` parameter so went back to hard coding it. Probably a bug in the way I am passing the parameter—as I said I'm pretty rusty at R, and it's complicated by the fact that you need to pass a curried function in to pblapply.

There are reports of cookies working which makes sense as from the server end it knows the requests form part of one session; it's clumsy from a UX perspective though as it requires the user to copy the cookies and the user-agent string from the browser (and methods for extracting those vary across different browsers)...

**Comment by muschellij2** [comment]
If I put #4 in the comment, I believe it closes it, so I didn't want to do that.

Pleaes send the PR so I can look at the diff

**Comment by matthewberryman** [comment]
Putting the issue number only closes the issue if you use a keyword and that commit's in the default branch per https://help.github.com/articles/closing-issues-using-keywords/
otherwise it will keep the issue open and insert a link to that commit in the issue thread, which I find handy.

I have reluctantly submitted the PR in #5 (I don't like submitting PRs with ugly stuff like hard coded things, also a super elegant solution would be to retry after a delay the first request that hit a 503, and then dynamically adjust delay after that).

**Comment by muschellij2** [comment]
I am going to deny PR #5 because it doesn't look like you pulled before working on this and I don't want a hard-coded sleeper.  I'm going to implement the sleeper for the gcite_citation_page.  

You should be able to run sleeptime now:
```r
xx = gcite(user = "vqD_0uQAAAAJ", sleeptime = 10)
```

This is more of a small pet project of mine, so that's about how much I can spend on it for the next few weeks.

So I'm going to close for now.  Please re-open with a PR if you think those additional 503 problems need to be corrected.

**Comment by matthewberryman** [comment]
I did work to put it in per https://github.com/muschellij2/gcite/pull/5/files and added parameters, just couldn't get the parameters flowing through properly in testing (and only submitted PR per your request just so it makes it easier to see what has been done so far). (Edit:) your changes work.

**Comment by matthewberryman** [comment]
Sorry I see you also added stuff in this commit https://github.com/muschellij2/gcite/commit/83b8a4dcaa3b13eb1f9010e2591b32e7628fdade where you took an alternative approach to currying, so that should work. I'll test now.

**Comment by matthewberryman** [comment]
Yep, all good - thanks.
